### PR TITLE
Aif v210

### PR DESCRIPTION
**Pull request by arnova**
Some major updates/refactoring. Most important changes concern dynamic host handling and implementation of a new job manager to accommodate improved (plugin) helper support. It also moves some duplicate code from the plugins to environment (like locking for instance).

Note that plugins using helpers are NOT backwards compatible with older AIF versions

### CODE REVIEW

**Comment by arnova** [comment]
@abelbeck : Mind having a look at this? It's still WIP and untested but you get the idea ;-)

**Comment by abelbeck** [comment]
Hi @arnova ,

Interesting, some time ago our (AstLinux) project rewrote all the plugins with `cron` helpers to instead use a constant `bash` background helper script for each plugin.  We "idle" using `sleep 1` in the background script so it can be cleanly terminated quickly, and to keep the `sleep 1` from spawning a new process we compile the bash "sleep" builtin and load it: `enable -f /usr/lib/bash/sleep sleep`

While this as worked well for us, (since busybox `cron` is very chatty to syslog), I can't say this would be the best general purpose solution for AIF ... or would it hmmm.

I had considered creating a single `bash` background helper script that all our custom plugins could leverage off of (similar to what you propose here) but after thinking about the amount of work required to rewrite a working solution, I dropped the idea. :-)

I'll be happy to look over this PR.  I'm wondering how our project would disable any new `cron`  "JOBS" stuff.

**Comment by arnova** [comment]
@abelbeck, actually I already had the background process solution in the back of my mind though I initially opted for the cron-solution. The background process has the advantage of not requiring cron AND finer grained control of eg. the intervals. The only 2 drawbacks I'm seeing are (a little) overhead and (a little) more complexity. I'm not familiar with the sleep builtin solution you're mentioning, but if we agree we drop cron in favor of our own process, you can take care of that bit. One other thing: do you know a clean/easy way to kill such a background process (eg. when aif is stopping)?

**Comment by arnova** [comment]
@abelbeck : Added a bunch of new commits including one that replaces cron with our own process. Note that the usage of pgrep/pkill doesn't seem to work properly at the moment and also locking needs some additional "care".

**Comment by abelbeck** [comment]
@arnova The best way to describe how AstLinux uses background helper processes is with the `dyndns-host-open` plugin example.

The dyndns-host-open helper is called here:

https://github.com/astlinux-project/astlinux/blob/master/package/arnofw/dyndns-host-open/50dyndns-host-open.plugin.sh#L149

and here:

https://github.com/astlinux-project/astlinux/blob/master/package/arnofw/dyndns-host-open/50dyndns-host-open.plugin.sh#L173

and stopped here:

https://github.com/astlinux-project/astlinux/blob/master/package/arnofw/dyndns-host-open/50dyndns-host-open.plugin.sh#L187

and optional "status" here:

https://github.com/astlinux-project/astlinux/blob/master/package/arnofw/dyndns-host-open/50dyndns-host-open.plugin.sh#L208

The actual helper is:

https://github.com/astlinux-project/astlinux/blob/master/package/arnofw/dyndns-host-open/dyndns-host-open-helper.sh

Note how the helper script is designed to only exit when `ARGSFILE` is removed and checked during `idle_wait()` so it happens quickly (within 1 second).  This is to assure no half-baked rule states, somewhat mimics how a `cron` called script would work.

The optional sleep builtin is an optimization, not sure where Debian locates these, but we could test for it.  It may require an optional `bash` package to install if wanted.

https://github.com/astlinux-project/astlinux/blob/master/package/arnofw/dyndns-host-open/dyndns-host-open-helper.sh#L20

Currently AstLinux has a self-contained background helper for each plugin that needs it.

Finally, if you want a single job-process for all the plugin helpers to attach to, before starting/stopping plugins I would stop all the helpers and then stop the master job-process.  Then after all the plugins have started "if" any plugin published a helper, only then would the master job-process be started to handle one or more plugin helpers.

**Comment by arnova** [comment]
@abelbeck : Do you think with what we have now in this PR, we can sync/merge it with your AstLinux implementation?

**Comment by abelbeck** [comment]
@arnova 

> I'm thinking about reimplementing some kind of pkill at start to make sure any hanging background processes are killed first. Thoughts?

I'm thinking if you need to do a `pkill` we did not do things correctly. :-)

> Do you think with what we have now in this PR, we can sync/merge it with your AstLinux implementation?

Sorry, my plate is full at this moment, I have not looked as closely into this PR as I need.

Though you seem to be doing quite well, keep it going ...

**Comment by abelbeck** [comment]
@arnova , regarding b187f70 why not call the helper directly rather then sourcing it into a separate script ?  I also see you are sourcing the helper into a function ... I think I tried this in the past and it worked, but is it POSIX to allow

```
foo()
{
  bar()
  {
    echo "bar"
  }

  bar
}
```

**Comment by arnova** [comment]
@abelbeck : I've slightly changed the jobs process logic now. Calling it directly means a lot of code duplication in each helper for eg. loading environment, main config etc. Sourcing has the downside of being able to tear down the jobs process in case one of the helpers malfunctions. I therefor introduced a stub loader (aif-job-execute) to fix both issues. Let me know what you think.

**Comment by abelbeck** [comment]
@arnova , OK but in the `aif-job-execute` script why are you using nested functions ?  Couldn't the `job_execute()` function be eliminated and contents placed at the end of the `aif-job-execute` script (`return` replaced with `exit`) ?

Another thought, I see you chose to reduce the time resolution to 1 minute from 1 second, I think seconds is better, IMO.

**Comment by arnova** [comment]
@abelbeck : The idea was the add locking to aif-job-execute so only one helper can run at a time. For that to work helpers shouldn't (early) exit but always return to the "caller". Perhaps you have an idea how to properly do that?

You mean second resolution in job-processor? Why do we need that?

**Comment by abelbeck** [comment]
@arnova I guess I'm not being clear ... in your `aif-job-execute` script 
```
# Job (helper) executer
job_execute()
{
  # Source helper
  . "$JOB_HELPER_PATH"

  # Execute job helper
  if ! job_helper_main; then
    return 1
  fi

  return 0
}
```
when sourcing `JOB_HELPER_PATH` it adds functions, hence creating nested function calls, ie:
```
job_execute()
{
  job_helper_main()
  {
  }
}
```
It looks like the `job_execute` function can be eliminated and source `JOB_HELPER_PATH` at the end.

> You mean second resolution in job-processor? Why do we need that?

On principle mostly, someone may want to run a helper every 90 seconds.

**Comment by arnova** [comment]
Ah yes 90 seconds intervals could be useful. 

I think I understand what you mean concerning the aif-job-execute script. The only thing I'm still not sure about is whether I'll stick with the "job_helper_main()" solution or that we make it in line with how we do it in the plugins by just sourcing + setting PLUGIN_RET_VAL. What do you think?

**Comment by abelbeck** [comment]
@arnova I like your changes.

> The only thing I'm still not sure about is whether I'll stick with the "job_helper_main()" solution or that we make it in line with how we do it in the plugins by just sourcing + setting PLUGIN_RET_VAL. What do you think?

I think `logger` would be the best method for notifications of the background helpers.

The plugin itself should handle any sanity checking when it starts, the helper scripts do not need any configuration sanity checks, but helper runtime errors can be logged with `logger`.

**Comment by arnova** [comment]
@abelbeck : The plugins can't sanity check everything upfront. That's one of the reasons plugins with helpers also have the option to run the helper at startup. So I do like to have some kind of error retrieval from helpers (next to using logger btw, which I already had on my todo-list). So the question remains: which of the 2 approaches I suggested do you prefer?

**Comment by abelbeck** [comment]
@arnova Can your give an example where a plugin can't sanity check for it's helper ?

The plugin will always start before it's helper, correct ?

**Comment by arnova** [comment]
@abelbeck : The rule parser fails in the helper. In theory we could check all this stuff up front, but currently we don't. Yes plugin always starts before helper (as it needs to do a "job_add" to enable the helper).

**Comment by abelbeck** [comment]
@arnova OK, good point, but without looking into detail, IIRC the helpers I wrote mostly add/remove rules to chains pre-defined via the plugin ... for those cases a `logger` error would be fine if a rule with a garbage address failed.

**Comment by abelbeck** [comment]
@arnova 
> Mind let me know what you think about the changes in this commit?

Which commit are you referring to ?  Or PR in general ?

**Comment by abelbeck** [comment]
@arnova It no longer works with the Busybox nslookup, example output...
```
# nslookup abelbeck.org
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost.priv.abelbeck.com

Name:      abelbeck.org
Address 1: 104.31.83.17
Address 2: 104.31.82.17
Address 3: 2400:cb00:2048:1::681f:5211
Address 4: 2400:cb00:2048:1::681f:5311
```
Though I did a quick test on Mac OS X, and the new `dig()` function worked with both `dig` and `nslookup`.

BTW, our AstLinux project does not use the `dig()` function, rather we let `iptables` resolve the multiple `A` and `AAAA` records.

**Comment by arnova** [comment]
@abelbeck : Added a commit that should fix the busybox nslookup issue. Please verify.

**Comment by abelbeck** [comment]
@arnova 
> Do you know why it doesn't work with busybox nslookup? Can you provide any error output?

Yes, per the output above, Busybox numbers the output `Address 1:`, etc., your new `awk` code does not match that.  As such no output is generated.

> Will iptables create entries automatically in case you hand it a hostname which resolves to multiple IPs?

Yes, we have used the multiple record feature for years with the `dyndns-host-open` plugin, though standard AIF may have other plugins that use `dig`, we don't install all of them.

astlinux/package/arnofw/dyndns-host-open/
https://github.com/astlinux-project/astlinux/tree/master/package/arnofw/dyndns-host-open

We also have IPv6 plugins that let `ip6tables` resolve hostnames.

**Comment by abelbeck** [comment]
@arnova 
>  Added a commit that should fix the busybox nslookup issue. Please verify.

Better, but now matches IPv6 address as well.

Also a reverse DNS can occur after the numeric IP
```
Address 1: 1.2.3.4 wsip-1-2-3-4.om.om.cox.net
```
For the nslookup case, it may be simpler to re-start with what worked before.

**Comment by arnova** [comment]
@abelbeck : Updated as suggested. Please review/test once again

**Comment by abelbeck** [comment]
@arnova Much better, seems to work, only difference is the multiple IPv4's are separated by a space rather then a NL.

**Comment by arnova** [comment]
@abelbeck : Perhaps it would be even better to use a comma as a separator since you can directly feed it to iptables then... (?)

**Comment by abelbeck** [comment]
@arnova 
> Perhaps it would be even better to use a comma as a separator since you can directly feed it to iptables then... (?)

Keep it general, comma delimiters seems too specific.

**Comment by arnova** [comment]
@abelbeck : Then I'll stick to space, which is much easier to process than a NL

**Comment by abelbeck** [comment]
@arnova 
> Then I'll stick to space, which is much easier to process than a NL

Good, but to be fair, `unset IFS` handles spaces and NL's equally well.

**Comment by arnova** [comment]
@abelbeck : Yes I know, but I was thinking about oneliners with cut/sed/awk

**Pull request merged**
