### PR TITLE
Move NAT_IF handling into environment

### PR DESCRIPTION
**Pull request by arnova**

### CODE REVIEW

**Comment by arnova** [comment]
@abelbeck : Please comment/review. I skipped the plugin changes for now, as that will also introduce backward compatibility issues. Do you see any immediate issue with that?

**Comment by abelbeck** [comment]
@arnova Your PR looks good to me.

With respect to the plugins, you are worried a changed plugin will be used with an older environment script ?, OK how about making this simple tweak to the plugins in the appropriate NAT related places:
```
-    for eif in $EXT_IF; do
+    for eif in ${NAT_IF:-$EXT_IF}; do
```
The latest environment will define NAT_IF, else it will fall back to EXT_IF when not defined.

(yes, works with dash :-) )

**Comment by abelbeck** [comment]
Ahhh, you might make a small comment tweak for NAT_STATIC_IP
```
 # interfaces, check the README file for more info). Note that the order of IPs
 # should match the order of interfaces (they belong to) in $EXT_IF!
 # -----------------------------------------------------------------------------
 #NAT_STATIC_IP="193.2.1.1"
```
to
```
 # should match the order of associated interfaces in $EXT_IF (or $NAT_IF if defined).
```

**Comment by arnova** [comment]
Ah yes, should be tweaked.

Good suggestion about NAT_IF:-$EXT_IF. However I still have doubts about which plugins should do this....

**Comment by abelbeck** [comment]
@arnova I looked more closely and here are my thoughts...

Plugin: 90outbound-snat.plugin
```
  for eif in $(wildcard_ifs $EXT_IF); do
    -j SNAT --to-source
  for eif in $EXT_IF; do
    -j SNAT --to-source
```
My Thoughts: $EXT_IF -> ${NAT_IF:-$EXT_IF}

Plugin: 90dmz-dnat.plugin
```
  for eif in $EXT_IF; do
    -j RETURN
  for eif in $EXT_IF; do
    -j DNAT --to-destination
  for eif in $EXT_IF; do
    -j ACCEPT
```
My Thoughts: $EXT_IF -> ${NAT_IF:-$EXT_IF}

Plugin: 50ipsec-vpn.plugin
```
  for eif in $EXT_IF; do  && for net in $INTERNAL_NET; do
    -m policy --pol ipsec --dir in -j RETURN
  for eif in $EXT_IF; do
    -m policy --pol ipsec --dir in -j ACCEPT
    -m policy --pol ipsec --dir out -j ACCEPT
  for eif in $EXT_IF; do  && for net in $INTERNAL_NET; do
    -m policy --pol ipsec --dir in -j RETURN
```
My Thoughts: Only loop over the two "ip4tables -t nat" calls with ${NAT_IF:-$EXT_IF}, else use existing $EXT_IF as is

Plugin: 20nat-loopback.plugin
```
  for eif in $(wildcard_ifs $EXT_IF); do
  if parse_rule "$rule" NAT_FORWARD_TCP "interfaces:EXT_IF-destips-shosts-ports-dhost_dport"; then
  if parse_rule "$rule" NAT_FORWARD_UDP "interfaces:EXT_IF-destips-shosts-ports-dhost_dport"; then
```
My Thoughts: $EXT_IF -> $NAT_IF and use parse_rule types (see below): "interfaces:NAT_IF-destips-shosts-ports-dhost_dport"
Note: Can't use ${NAT_IF:-$EXT_IF} consistently here, so use NAT_IF

In the main script:
Rules NAT_FORWARD_xxx currently use "interfaces:EXT_IF-..."
```
    if parse_rule "$rule" NAT_FORWARD_TCP "interfaces:EXT_IF-destips-shosts-ports-dhost_dport"; then
    if parse_rule "$rule" NAT_FORWARD_UDP "interfaces:EXT_IF-destips-shosts-ports-dhost_dport"; then
    if parse_rule "$rule" NAT_FORWARD_IP "interfaces:EXT_IF-destips-shosts-protos-dhost"; then
```
replace with "interfaces:NAT_IF-..."
```
    if parse_rule "$rule" NAT_FORWARD_TCP "interfaces:NAT_IF-destips-shosts-ports-dhost_dport"; then
    if parse_rule "$rule" NAT_FORWARD_UDP "interfaces:NAT_IF-destips-shosts-ports-dhost_dport"; then
    if parse_rule "$rule" NAT_FORWARD_IP "interfaces:NAT_IF-destips-shosts-protos-dhost"; then
```
and then add a 'parse_rule()' type:
```
  interfaces:NAT_IF-destips-shosts-ports-dhost_dport|interfaces:NAT_IF-destips-shosts-protos-dhost)
```

Lastly, while the ```${NAT_IF:-$EXT_IF}``` does offer compatibility for old plugins, is this a real problem ?  If we could simply use ```$NAT_IF``` and expect the plugins to track the environment script, that would be better IMHO.  We are already assuming the main scrip tracks the environment script.

**Comment by abelbeck** [comment]
@arnova Any thoughts on polishing off your new NAT_IF option wrt plugins and NAT_FORWARD_xxx rules ?

**Comment by arnova** [comment]
@abelbeck : Sorry I missed that email, see it now. Don't hesitate to ping me on tickets in case I don't reply (unless I'm on vacation).

**Comment by arnova** [comment]
I think it will workout for any scenario anyway (from the user's perspective). That being said I think what you're proposing seems like a good solution for handling NAT_IF.

**Comment by abelbeck** [comment]
Can we assume the plugins will track the main script or should we include the backword-compatibility discussed above ?

**Comment by abelbeck** [comment]
I'm now leaning toward always using ```${NAT_IF:-$EXT_IF}``` instead of defining ```NAT_IF``` in environment and replacing ```$EXT_IF``` here and there.  I'm thinking ```${NAT_IF:-$EXT_IF}``` self-documents what is happening better.  And it doesn't occur in too many places.

Though if you prefer always defining ```NAT_IF``` in environment, I'd be on board with that also.

**Comment by arnova** [comment]
For consistency it would be nice to also have it defined in environment. I'm fine with also having the EXT_IF fallback in the plugins for legacy support, but I doubt there are many folks out there that actually use an AIF with separated (newer) plugins.

**Comment by abelbeck** [comment]
OK, I'll put together all these ideas into a commit to polish off ```NAT_IF``` support.

**Comment by abelbeck** [comment]
@arnova FYI - I have 2.0.1g-RC1 on my production box (AstLinux) and now NAT_IF does not include the ip6tun (IPv6 he.net tunnel) interface that EXT_IF does, works perfectly, and with fewer rules.

**Comment by arnova** [comment]
@abelbeck : Excellent! Thanks a bunch!

**Comment by arnova** [comment]
@abelbeck: Just making sure: This PR is obsolete, right?

**Comment by abelbeck** [comment]
@arnova :  Yes, this PR is obsolete  ... implemented elsewhere.

**Pull request closed without merging**
