### PR TITLE
Stale lock fix

### PR DESCRIPTION
**Pull request by arnova**
This should improve/fix the previously implemented stale lock file handling.

### CODE REVIEW

**Comment by arnova** [comment]
@abelbeck : Please review/comment. If you're fine with it feel free to merge.

**Comment by abelbeck** [comment]
@arnova Interesting idea to put the
```
while [ $cnt -gt 0 ] && [ -f "$LOCK_FILE" ]; do
```
loop in ```plugin_start()``` instead of ```plugin_stop()``` giving more time for the helper to finish.

On the negative side, a real stale lockfile will delay startup by 5 seconds, also the helper accesses the DYNDNS_CHAIN/ACCOUNTING_* chains.  If the helper-down-wait loop was in ```plugin_stop()``` it seems a better place to me before those chains are removed.

Your ```pgrep -l``` is Busybox friendly, but given the ```echo "$$"``` generated lockfile I'm not seeing any output from ```pgrep -l PID``` maybe you are ?  Possibly just removing...
```
        PROCESS="$(pgrep -l "$(cat "$LOCK_FILE")")"
        printf "Held by:\n${PROCESS}\n" >&2
```
is good ?  Besides, we know the "Held by:" answer don't we ?

**Comment by arnova** [comment]
Yeah we probably know where the lock came from. It's just a silly c&p from another project of mine. I think indeed just doing the while loop in stop may be the best approach after all.

**Comment by arnova** [comment]
@abelbeck : Updated

**Comment by arnova** [comment]
ps. Don't understand why the pgrep doesn't work, I recall testing that (obviously) but now it somehow fails to work.

**Comment by abelbeck** [comment]
@arnova As far as pgrep, this lists the sub-processes of the helper process:
```
pgrep -l -P "$(cat "$LOCK_FILE")"
```
But I question if this info is useful enough to display, possibly confusing, and adds another command requirement (though usually available).

Your changes look good, I'll merge.

**Pull request merged**
