### PR TITLE
changed: Improve locking and implement handling for stale lockfiles

### PR DESCRIPTION
**Pull request by arnova**

### CODE REVIEW

**Comment by arnova** [comment]
@abelbeck : Please review. Could you specifcally check whether the kill and sh -c PPID stuff works on AstLinux/BusyBox ?

**Comment by abelbeck** [comment]
I breadboarded the new functions and it works with AstLinux/busybox, in particular ```sh -c 'echo $PPID'``` and ```kill -0 $PID``` work as expected.

A couple comments/questions:

1) Since both scripts are run as /bin/bash, the original ```echo "$$"``` yields the same result as ```sh -c 'echo $PPID'``` and is simpler.

2) When does ctrl_handler() get a $1 passed to it ?  The trap calls it without an argument it would seem.

3) Taking a step back, is the reason a stale lockfile is even possible is the fact you are using /var/tmp/... for the lockfile which is typically on persistent storage and survives a reboot ?  If you used /var/lock/... instead most systems (Debian, RedHat, AstLinux, ...) mount /var/lock on tmpfs (either directly or via /run/)

Possibly this is a simpler solution:
```
- LOCK_FILE="/var/tmp/aif_dyndns_helper.lock"
+ LOCK_FILE="/var/lock/aif_dyndns_helper.lock"

- LOCK_FILE="/var/tmp/aif_traffic_accounting_helper.lock"
+ LOCK_FILE="/var/lock/aif_traffic_accounting_helper.lock"
```

In AstLinux, years ago, we re-wrote the "dyndns-host-open.plugin" to not use cron, but instead a background helper process and we use:
```
LOCKFILE="/var/lock/aif_dyndns_host_open.lock"
```

**Comment by arnova** [comment]
@abelbeck : I've seen stale lock files also while not rebooting. Not sure where it exactly came from but it certainly seems like a problem we should address properly. Even though using /var/lock may be nicer, I still like some logic to handle the corner-cases, just in case. The reason I switched to sh -c $PPID instead of $$ is because it's more reliable. In this case it doesn't matter but when one would use a forked process $$ returns the parent PID, not the child PID which causes problems. Note that this may already be a problem for your background helper. Note that I use these functions in several scripts I wrote that's why they may contain generic stuff that isn't specifically used here.

**Comment by abelbeck** [comment]
> The reason I switched to sh -c $PPID instead of $$ is because it's more reliable. In this case it doesn't matter but when one would use a forked process $$ returns the parent PID, not the child PID which causes problems.

Using this test script ```$$``` and ```sh -c 'echo $PPID'``` are always the same for me:
```
#!/bin/bash

TEST_FILE="/tmp/aif_foo_bar"

sh -c 'echo $PPID' > $TEST_FILE
sh_ppid="$(cat $TEST_FILE)"
rm $TEST_FILE

logger -s "Compare native bash process id=$$ with subprocess parent id=$sh_ppid"
```

Back to the OT, while I have never seen any stale lockfiles on tmpfs storage in my experience, it would be interesting to understand how it is happening.

Otherwise your PR code looks fine to my eye, though I would cleanup the unused ```$1``` arg in ```ctrl_handler()```.

**Comment by arnova** [comment]
Lonnie try:
....
child_process()
{
  echo "$$" # Will give PID of the parent process (wrong)
#or 
  echo "$(sh -c $PPID)" # Will give the PID of the spawned child process (correct)
}

child_process &
......

I think I got a stale lockfile a few times when playing with cron and/or tmpfs, not sure. It probably happened when I was fiddling with a new script I wrote which allows some of the /var stuff to be on a shadow tmpfs volume to allow hdd spindown. 

And yes, will cleanup the unused $1.

**Comment by abelbeck** [comment]
> child_process &

No, /bin/bash $$ is the current script process, "$(sh -c $PPID)" will give the PID of the temporary spawned subshell, which will be always different. ```sh -c $PPID``` not in $() or backticks should be the same as ```$$```.

**Comment by arnova** [comment]
@abelbeck : Ok, my exaple with $() as wrong (but that's not how I used it anyway). But for what I've tried here it certainly made a difference:
#!/bin/sh

procs()
{
  echo "child1: $$"
  child2=`sh -c 'echo $PPID'`
  echo "child2: $child2"
  echo "child3: $(sh -c 'echo $PPID')"
}

echo "parent $$"
procs &

Will yield:
parent 10425
child1: 10425
child2: 10426
child3: 10426

So only the 2 latter options will work when using locking for a background process.

**Comment by abelbeck** [comment]
The bash ```$$``` variable is the script's process id, not the script's parent.  Add a ```sleep 20``` to the end of my test script above and prove that to yourself.

I agree calling ```proc``` as a background process would have a different PID than the original script, but that is not the case in this context.

It would seem in this case ```$$``` would give you the proper result without spawning a shell instance.

**Comment by arnova** [comment]
@abelbeck : I've updated it. But keep in mind that if you guys at Ast use it as a background process the $$ won't work, in that case you really need the sh -c trick. Unless you ofc keep it locked all the time while it's running (also during sleep) but that would sort of beat it's purpose (& advantage)....

**Comment by abelbeck** [comment]
@arnova Looks good.

One minor thing, in `lock_leave()` you swapped the order of removing the lockfile and disabling the trap from the origional code.  In the unlikely event an interrupt occurred immediately after disabling the trap, then a stale lockfile would remain.  I think the original order (rm then trap) is better.

BTW, a git question, how did you update this PR with still only a singe commit message ?  Is that some sort of git rebase thing ?

**Comment by arnova** [comment]
@abelbeck : Good point, I swapped them.

About GIT: there are several ways you could do this. This simplest one is edit files, perform "git commit -a --amend" followed by a forced push with "git commit -f origin {branch}". Alternatively you can perform a squash by first adding a regular commit and then perform a "git rebase -i HEAD~{number of commits}" + in the editor insert squash for the commits that need to be squashed, again followed by a forced push.

**Comment by abelbeck** [comment]
@arnova you have seem to reverted some of the earlier changes, like `$1` in `ctrl_handler()`.

Thanks for the git tips !

**Comment by arnova** [comment]
@abelbeck : Will fix.

If you like I can pass you my GIT cheatlist....

**Comment by arnova** [comment]
btw. That's the danger of forced push: If you forget to first pull on another computer, you screw up your branch with forced push :/

**Comment by abelbeck** [comment]
@arnova I think you are still behind earlier commits, `$$` and /var/lock/... changes

> If you like I can pass you my GIT cheatlist....

I have your GIT cheat-sheet from a few years ago, but If it is updated, yes please.

**Comment by arnova** [comment]
Thanks for the heads up. I also forgot the lockfile-paths in the plugin themselves. All should be ok now :)

**Comment by abelbeck** [comment]
Looks good.  Merge it !

Are we getting close to an official 2.0.2 release ?

**Comment by arnova** [comment]
Dunno. Any idea about the open issues that are currently still here on Github?

**Comment by abelbeck** [comment]
2 of the open Issues are yours :-)  The other is a plugin suggestion without any followup.

**Pull request merged**
