### PR TITLE
Disable automatic helper assignment, attach with CT target, fixes Issue #35

### PR DESCRIPTION
**Pull request by abelbeck**
… but still a few rough edges,

The PPTP helper needs to be IPv4-only

All in all, fewer changes that I had initially planned.

### CODE REVIEW

**Comment by abelbeck** [comment]
@arnova This PR is working well for me.

BTW, if a user wanted a TFTP helper enabled they could add a custom rule:
```
load_conntrack_helper_module tftp udp 69
````

Also note that we are leveraging on the existence of ```net.netfilter.nf_conntrack_helper``` to use "-m conntrack --ctstate", else fallback to using "-m state --state".  There is quite a range of kernels/iptables that support either, but it is nice to use them consistently.

**Comment by arnova** [comment]
Overall looking very nice and clean and working well :-) Please check the few comments I've made.

**Comment by abelbeck** [comment]
Hmmm, I can't find the comments you made.  Where should I be looking ?

**Comment by arnova** [comment]
The vpn & soip plugins. Can't you see the diff above here?

**Comment by abelbeck** [comment]
> The vpn & soip plugins. Can't you see the diff above here?

No, I don't see any, no "comment bubbles" either.

Here is the "conntrack" branch in my tree:
https://github.com/abelbeck/aif/tree/conntrack

**Comment by arnova** [comment]
Strange, I can see them here in Chrome

**Comment by abelbeck** [comment]
I was using Safari and iOS, now they appear, very weird.

**Comment by abelbeck** [comment]
I implemented your suggestions, quickly tested OK.

Anything else I should look at ?  Or the "Merge pull request" is your's to click :-)

**Comment by arnova** [comment]
Ignore my comments about the legacy module support. I didn't notice the section below it. One thing came to mind and that is that I believe this justifies a version bump to 2.02(-BETA/RC ?), agreed?

**Comment by abelbeck** [comment]
Sure, 2.02-RC1 sounds good to me.  Do you want me to merge this PR (or you can) and then I can create a  2.02-RC1 tag/release for testing?

**Comment by arnova** [comment]
Sure, feel free!

**Pull request merged**
